name: ci
on:
  push:
    branches:
      - develop
      - ci-setup
  pull_request:
    branches:
      - develop
jobs:
  check-code-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.18
      - run: npm ci --prefer-offline --no-audit --no-save
      - run: npm run check-format

  test:
    needs: check-code-formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.18
      - run: npm ci --prefer-offline --no-audit --no-save
      - run: npm run build
      - run: npm run test
